
development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  username: 
  password:
  host: localhost
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test